name: CPP binary SDK packaging
on:
  workflow_dispatch:
    inputs:
      commitId:
        description: 'commit ID to package'

env:
  # Packaging prerequisites
  # Binutils 2.34 released Feb 1, 2020
  binutilsVer: 2.34
  # Demumble 1.1.0 released Nov 13, 2018
  demumbleVer: 1.1.0

jobs:
  test_matrix:
    name: test-matrix-${{ matrix.sdk_platform }}${{ matrix.suffix }}
    runs-on: ${{ matrix.runs_on_platform }}
    strategy:
      fail-fast: false
      matrix:
        sdk_platform: [linux, darwin, windows]
        suffix: ['']
        runs_on_platform: [ubuntu-latest]
        include:
        - sdk_platform: windows
          suffix: '-x86-Release-static'
        - sdk_platform: windows
          suffix: '-x86-Release-dynamic'
        - sdk_platform: windows
          suffix: '-x64-Release-static'
        - sdk_platform: windows
          suffix: '-x64-Release-dynamic'
        - sdk_platform: windows
          suffix: '-x86-Debug-static'
        - sdk_platform: windows
          suffix: '-x86-Debug-dynamic'
        - sdk_platform: windows
          suffix: '-x64-Debug-static'
        - sdk_platform: windows
          suffix: '-x64-Debug-dynamic'
        - sdk_platform: darwin
          runs_on_platform: macos-latest
        exclude:
        - sdk_platform: windows
          suffix: ''
        - sdk_platform: darwin
          runs_on_platform: ubuntu-latest
    steps:
      - name: test run
        run: |
          set -x
          uname
          uname -a
          echo SDK ${{ matrix.sdk_platform }}
          echo Running on ${{ matrix.runs_on_platform }}

