name: CPP binary SDK packaging
on:
  workflow_dispatch:
    inputs:
      commitId:
        description: 'commit ID to package'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Commit ID: ${{ github.event.inputs.commitId }}"

  buildBinutils:
    runs-on: ubuntu-latest
    steps:
      - name: fetch binutils source
        run: curl -L https://ftpmirror.gnu.org/binutils/binutils-2.34.tar.xz binutils-2.34
      - name: untar binutils source
        run: tar -xvzf binutils-2.34.tar.xz
      - name: configure binutils
        run: ./configure --enable-targets=all --prefix=/tmp/binutils
        working-directory: ./binutils-2.34
      - name: make binutils
        run: make
        working-directory: ./binutils-2.34
      - name: install binutils in /tmp/binutils
        run: make install
        working-directory: ./binutils-2.34
