name: CPP binary SDK packaging
on:
  workflow_dispatch:
    inputs:
      commitId:
        description: 'commit ID to package'

env:
  # Packaging prerequisites
  # Binutils 2.34 released Feb 1, 2020
  binutilsVer: 2.34
  # Demumble 1.1.0 released Nov 13, 2018
  demumbleVer: 1.1.0

jobs:
  build_tools:
    name: build-packaging-tools
    runs-on: ubuntu-latest
    steps:
      - name: fetch and build binutils
        run: |
          curl -L https://ftpmirror.gnu.org/binutils/binutils-${{ env.binutilsVer }}.tar.xz --output binutils.tar.xz
          tar -xf binutils.tar.xz
          mv ./binutils-${{ env.binutilsVer }} ./binutils-src
          cd binutils-src
          ./configure --enable-targets=all --prefix=/tmp/binutils
          make
          make install
          cd ~
      - name: fetch demumble
        uses: actions/checkout@v2.3.1
        with:
          repository: nico/demumble
          path: demumble-src
          ref: v${{ env.demumbleVer }}
      - name: build demumble
        run: |
          cd demumble-src
          cmake .
          cmake --build .
          python demumble_test.py
          cp -af ./demumble /tmp/demumble
          cd ~
      - name: archive packaging tools
        run: tar cvzf ~/packaging_tools.tgz demumble binutils/ar binutils/nm-new binutils/objcopy
      - name: upload packaging tools artifact
        uses: actions/upload-artifact@v2
        with:
          name: packaging-tools
          path: packaging_tools.tgz

  build_ios:
    name: build-sdk-ios-${{ matrix.architecture }}
    runs-on: macos-latest
    strategy:
      matrix:
        architecture: [arm64, x86_64]
    steps:
    - name: fetch SDK
      uses: actions/checkout@v2.3.1
      with:
        path: sdk-src
        ref: ${{ github.event.inputs.commitId }}
    - name: install prerequisites
      run: sdk-src/build_scripts/ios/install_prereqs.sh
    - name: build sdk
      run: |
        build_scripts/ios/build.sh firebase-cpp-sdk-ios-${{ matrix.architecture }} sdk-src ${{ matrix.architecture }}
        tar -cvzf firebase-cpp-sdk-ios-${{ matrix.architecture }}.tgz firebase-cpp-sdk-ios-${{ matrix.architecture }}
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firebase-cpp-sdk-ios-${{ matrix.architecture }}
        path: firebase-cpp-sdk-ios-${{ matrix.architecture }}.tgz

  build_android:
    name: build-sdk-android
    runs-on: ubuntu-latest
    steps:
    - name: fetch SDK
      uses: actions/checkout@v2.3.1
      with:
        path: sdk-src
        ref: ${{ github.event.inputs.commitId }}
    - name: install prerequisites
      run: sdk-src/build_scripts/android/install_prereqs.sh
    - name: build sdk
      run: |
        build_scripts/android/build.sh firebase-cpp-sdk-android sdk-src
        tar -cvzf firebase-cpp-sdk-android.tgz firebase-cpp-sdk-android
