name: CPP binary SDK packaging
on:
  workflow_dispatch:
    inputs:
      commitId:
        description: 'commit ID to package'

env:
  # Packaging prerequisites
  # Binutils 2.34 released Feb 1, 2020
  binutilsVer: 2.34
  # Demumble 1.1.0 released Nov 13, 2018
  demumbleVer: 1.1.0

jobs:
  build_tools:
    name: build-packaging-tools
    runs-on: ubuntu-latest
    steps:
      - name: fetch and build binutils
        run: |
          curl -L https://ftpmirror.gnu.org/binutils/binutils-${{ env.binutilsVer }}.tar.xz --output binutils.tar.xz
          tar -xf binutils.tar.xz
          mv ./binutils-${{ env.binutilsVer }} ./binutils-src
          cd binutils-src
          ./configure --enable-targets=all --prefix=/tmp/binutils
          make
          make install
          cd -
          mkdir -p packaging-tools
          cp -af /tmp/binutils/bin/ar /tmp/binutils/bin/nm /tmp/binutils/bin/objcopy packaging-tools
      - name: fetch demumble
        uses: actions/checkout@v2.3.1
        with:
          repository: nico/demumble
          path: demumble-src
          ref: v${{ env.demumbleVer }}
      - name: build demumble
        run: |
          cd demumble-src
          cmake .
          cmake --build .
          python demumble_test.py
          cd -
          mkdir -p packaging-tools
          cp -af demumble-src/demumble packaging-tools
      - name: archive tools
        run: tar -czhf packaging-tools.tgz packaging-tools
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packaging-tools
          path: packaging-tools.tgz

  build_package_ios:
    name: build-package-ios
    runs-on: macos-latest
    steps:
      - name: fetch SDK
        uses: actions/checkout@v2.3.1
        with:
          path: sdk-src
          ref: ${{ github.event.inputs.commitId }}
      - name: install prerequisites
        run: sdk-src/build_scripts/ios/install_prereqs.sh
      - name: build sdk
        run: |
          sdk-src/build_scripts/ios/build.sh -b firebase-cpp-sdk-ios-build -s sdk-src
          sdk-src/build_scripts/ios/package.sh firebase-cpp-sdk-ios-build firebase-cpp-sdk-ios-package
          cd firebase-cpp-sdk-ios-package
          tar -czhf ../firebase-cpp-sdk-ios-package.tgz .
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firebase-cpp-sdk-ios-package
          path: firebase-cpp-sdk-ios-package.tgz

  build_package_android:
    name: build-package-android-${{matrix.stl}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stl: ["c++", "gnustl", "stlport"]
    steps:
      - name: fetch SDK
        uses: actions/checkout@v2.3.1
        with:
          path: sdk-src
          ref: ${{ github.event.inputs.commitId }}
      - name: install prerequisites
        run: sdk-src/build_scripts/android/install_prereqs.sh
      - name: build sdk
        run: |
          sdk-src/build_scripts/android/build.sh firebase-cpp-sdk-android-${{ matrix.stl }}-build sdk-src ${{ matrix.stl }}
          sdk-src/build_scripts/android/package.sh firebase-cpp-sdk-android-${{ matrix.stl }}-build firebase-cpp-sdk-android-${{ matrix.stl }}-package ${{ matrix.stl }}
          cd firebase-cpp-sdk-android-${{ matrix.stl }}-package
          tar -czhf ../firebase-cpp-sdk-android-${{ matrix.stl}}-package.tgz .
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firebase-cpp-sdk-android-${{ matrix.stl }}-package
          path: firebase-cpp-sdk-android-${{ matrix.stl }}-package.tgz

  build_desktop:
    name: build-${{ matrix.sdk_platform }}-${{ matrix.architecture }}-${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        build_type: ["Release", "Debug"]
        architecture: ["x64",]
        python_version: [3.7]
        include:
        - os: windows-latest
          architecture: "x64"
          vcpkg_triplet: "x64-windows-static"
          msbuild_platform: "x64"
          sdk_platform: windows
          cmake_flags: ""
        - os: ubuntu-latest
          architecture: "x64"
          vcpkg_triplet: "x64-linux"
          sdk_platform: linux
          cmake_flags: ""
        - os: macos-latest
          architecture: "x64"
          vcpkg_triplet: "x64-osx"
          sdk_platform: darwin
          cmake_flags: "--target_format libraries"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          ref: ${{ github.event.inputs.commitId }}

      - name: Set env variables for subsequent steps (all)
        run: |
          echo "::set-env name=VCPKG_RESPONSE_FILE::external/vcpkg_${{ matrix.vcpkg_triplet }}_response_file.txt"
          echo "::set-env name=MATRIX_UNIQUE_NAME::${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}"
          echo "::set-env name=SDK_NAME::${{ matrix.sdk_platform }}-${{ matrix.architecture }}-${{ matrix.build_type }}"

      - name: Cache vcpkg C++ dependencies
        id: cache_vcpkg
        uses: actions/cache@v2
        with:
          path: external/vcpkg/installed
          key: dev-vcpkg-${{ matrix.vcpkg_triplet }}-${{ hashFiles(format('{0}', env.VCPKG_RESPONSE_FILE)) }}-${{ hashFiles('.git/modules/external/vcpkg/HEAD') }}

      - name: Cache ccache files
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        id: cache_ccache
        uses: actions/cache@v2
        with:
          path: ccache_dir
          key: dev-test-ccache-${{ env.MATRIX_UNIQUE_NAME }}

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.architecture }}

      - name: Install prerequisites
        run: |
          python scripts/gha/install_prereqs_desktop.py

      - name: Build SDK
        run: |
          python scripts/gha/build_desktop.py --arch "${{ matrix.architecture }}" --config "${{ matrix.build_type }}" --build_dir firebase-cpp-sdk-${{ env.SDK_NAME }}-build ${{ matrix.cmake_flags }}
          cd firebase-cpp-sdk-${{ env.SDK_NAME }}-build
          tar -czhf ../firebase-cpp-sdk-${{ env.SDK_NAME }}-build.tgz .

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firebase-cpp-sdk-${{ env.SDK_NAME }}-build
          path: firebase-cpp-sdk-${{ env.SDK_NAME }}-build.tgz

      - name: Stats for ccache (mac and linux)
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: ccache -s

  merge_packages:
    name: merge-packages
    runs-on: ubuntu-latest
    needs: [build_package_ios, build_package_android]
    steps:
      - name: fetch SDK
        uses: actions/checkout@v2.3.1
        with:
          path: sdk-src
          ref: ${{ github.event.inputs.commitId }}

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          # download-artifact doesn't support wildcards, but by default
          # will download all artifacts. Sadly this is what we must do.
          path: artifacts

      - name: merge SDK packages
        run: |
          set -ex
          mkdir -p firebase_cpp_sdk
          for pkg in artifacts/firebase-cpp-sdk-*-package/*.tgz; do
            tar -xzf "${pkg}" -C firebase_cpp_sdk
          done
          # Add the final files.
          sdk-src/build_scripts/other/package.sh sdk-src firebase_cpp_sdk
          tar -czhf firebase_cpp_sdk.tgz firebase_cpp_sdk

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firebase_cpp_sdk
          path: firebase_cpp_sdk.tgz
